### ISSUE TITLE
Enum serialized as empty array when using spatie/laravel-event-sourcing and spatie/data-transfer-object

### ISSUE THREAD

**Issue by eelmasllari** [spatie/enum#100]
When using enums inside a Spatie/DTO which is used for a StorableEvent, the Enum::jsonSerialize method never gets called and the enum gets saved as an empty array. (It might be a bug with the DTO or event sourcing package, but since you're working on those as well, I might as well report the bug where I see it :) 

The data is correct until Event sourcing's JsonEventSerializer::serialize() call;  Afterwards the enum gets replaced with an empty array.

(Heavily edited) files below: 
```
Enum: ReportType.php
-----------------------------------------------------------
<?php

use Spatie\Enum\Enum;

/**
 * @method static self detailed()
 * @method static self generic()
 */
class ReportType extends Enum
{

//N.B. it doesn't matter whether custom values are specified or not, it still gets serialized as empty array
    protected static function values(): array
    {
        return [
            'detailed' => 0,
            'generic' => 1,
        ];
    }
}


Data Transfer Object: Report.php
----------------------------------------------------
<?php

use Spatie\DataTransferObject\DataTransferObject;

class Report extends DataTransferObject
{
    public ?ReportType $type = null;
}



Stored Event: ReportReceived.php
--------------------------------------------------
<?php
use Spatie\EventSourcing\StoredEvents\ShouldBeStored;

class ReportReceived extends ShouldBeStored
{
    public Report $report;

    public function __construct(Report $report)
    {
        $this->report = $report;
    }
}


Emitting the event
--------------------
<?php

$report = new Report(['type' => ReportType::from('detailed')]);
event(new ReportReceived($report));


Event Stored in database:
----------------------------------------------
79|||App\Context\Reports\Events\ReportReceived|{"report":{"type":[]}}|[]|2021-05-24 09:14:38
```

**Comment by Gummibeer** [comment]
@brendt you work on the DTO package.
From my perspective the enum package does everything right as we offer several ways to (de)serialize the object.

**Comment by eelmasllari** [comment]
@Gummibeer @brendt I just refactored the code to not use a DTO and the problem is still there, i.e. it has nothing to do with the DTO. 

Events get normalized before serializing. Spatie's ObjectNormalizer::normalize (which extends Symfony's AbstractObjectNormalizer) calls ObjectNormalizer::getAttributes, which can't find any serializable attribute for the Enum:
- it looks for methods starting with "get", "has", or "is" -- but Enum has no such methods
- it looks for properties and finds "value" and "label", but they are not public in the Enum, so they are ignored
- Enum::jsonSerialize is never called (neither directly nor indirectly)

![image](https://user-images.githubusercontent.com/3466670/119350461-ab053800-bc9f-11eb-9da7-6e4326341cdc.png)

It seems to me that, although the "enum" and "laravel-event-sourcing" packages support serialization, they can't agree on a *common* way to (de)serialize Enums

**Comment by brendt** [comment]
This seems more like an issue for the event sourcing package, though I need to tell you that we're closing in on a new major version, which I think will solve this issue because of the serializer changes in it.
