### ISSUE TITLE
Strong typed enums problems

### ISSUE THREAD

**Issue by alkhachatryan** [spatie/enum#102]
I use laravel json API. I pass the json payload to the BE.
I have a X enum and changed the values to integers - to keep the integers in DB for better indexing.

When I pass  1 (integer) it passes the validation and record being created.
When I pass "1" (string) it passes the validation but in creation flow I 500 error:
_There's no value 1 defined for enum App\Enums\ENUM, consider adding it in the docblock definition_

This is validator:
`'enum_type' => ['required', 'integer', 'in:' . implode(',', Enum::toValues())],`

How to solve this? How to "tell" to the class that the digit can be both of string and/or integer types?

Enum class:
`protected static function values(): array
    {
        return [
            'enum1' => 1,
            'enum2' => 2,
        ];
    }`

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-enum/issues/57
