### ISSUE TITLE
Localised labels aren't update after locale is changed

### ISSUE THREAD

**Issue by renanbr** [spatie/enum#143]
Assuming `SomeEnum` is an enum which `protected static function labels(): array` result varies according to the locale. Labels are cached and never updated, even after changing the locale.

```php
App::setLocale('de_DE');

dump(SomeEnum::foo()->label); // expected: german, actual: german

App::setLocale('fr_FR');

dump(SomeEnum::foo()->label); // expected: french, actual: german
```

**Comment by Gummibeer** [comment]
That's intended as the behavior replicates the nom official enum and also how enums behave in other languages. If you want a dynamic label you should add a custom method that will return the always up to date translated label.
