### ISSUE TITLE
Add static return type for Enum::make to doc-block

### ISSUE THREAD

**Issue by brendt** [spatie/enum#22]

**Comment by Gummibeer** [comment]
@brendt what do you mean? The `Enum::make()` already has a return type.
```php
public static function make($value): Enumerable;
```

**Comment by brendt** [comment]
I mean a doc block return type, so that when calling `ConcreteEnum::make()` in your code, the IDE knows what type of enum you're working with :)

**Comment by brendt** [comment]
Added in 2.0.1: https://github.com/spatie/enum/releases/tag/2.0.1
