### ISSUE TITLE
Enum::toArray() bc break? bug?

### ISSUE THREAD

**Issue by josefsabl** [spatie/enum#27]
Enum::toArray() v1.0 used to return array as:

```
home => "home"
work => "work"
other => "other"
```

v2.0 returns

```
home => 0
work => 1
other => 2
```

Is this supposed to be like that? I find it counterintuitive. If this is a feature and not a bug it is definitely a bc break and should be noted in [changelog](https://github.com/spatie/enum/blob/master/CHANGELOG.md)

Anyway, thanks for this nifty library. Once we put it in production the postcard will definitely be on its way ;-)

**Comment by Gummibeer** [comment]
I've listed it in the changelog now. The BC release was done right `v1` to `v2`.

**Comment by josefsabl** [comment]
Ok.
