### ISSUE TITLE
Impossible to create custom static methods in extended class

### ISSUE THREAD

**Issue by josefsabl** [spatie/enum#28]
I wanted to create a backwards [compatible version](https://github.com/spatie/enum/issues/27) of toArray() in the extended Enum class only to find out that all static methods in extending classes are considered to be "magical" and generate values inside enum.

`
Return value of Spatie\Enum\Enum::make() must implement interface Spatie\Enum\Enumerable, array returned
`

The problem is in the \Spatie\Enum\Enum::resolveFromStaticMethods method.

I think there should be some mechanism to prevent this. At least make this more obvious than generating the cryptic error message.

**Comment by Gummibeer** [comment]
What do you expect? Without enforcing a class which implements the interface we can't handle objects.

And you can override it - but have to keep up the parameters and return values defined in the interface.

What do you try to do exactly? With a code snippet it would be easier to help and find a solution.

**Comment by josefsabl** [comment]
I wanted to do something like this:

```
class Enum extends \Spatie\Enum\Enum {
  public static function toArrayBcCompat(): array {
    $array = parent::toArray();
    return array_combine(array_keys($array), array_keys($array));
  }
}
```

And got the error as Spatie\Enum thinks that toArrayBcCompat is a value.

I think I understand why that is but there should be any way to circumvent the problem. Maybe some convention, annotation or anything?

See: https://github.com/spatie/enum/issues/27

**Comment by Gummibeer** [comment]
Ok, so we have two problems here:
* **bug**: overriding existing static methods
* **feature**: adding static methods which aren't an enum value

I will fix the bug first and after this try to implement the feature. Would you be fine with the old "private" method naming like `_ toArrayBcCompat()` or would you like an annotation more `@ignoreEnum` or something like this?

@brendt ideas?

**Comment by brendt** [comment]
@josefsabl can you explain what exactly you want to do with this BC array representation you mentioned in #27 ?

I'm unsure if we should add more functionality to the enum, or whether you specific problem can be solved in another way.

When I need enums in, for example, a select box in a form; I use a [view model](https://github.com/spatie/laravel-view-models) to build the options for this select box. I never immediately pass the enum data to a view file. It's my guess that you're trying to do something similar?

**Comment by Gummibeer** [comment]
@josefsabl `array_combine(array_keys($array), array_keys($array))` also isn't what was done before.
https://github.com/spatie/enum/pull/29/files#diff-2e72672854b6d283c2bfa0177d475bf8 uses the old logic `value => name`. With the only difference that the `name` is uppercased instead of lowercased now.

**Comment by josefsabl** [comment]
> can you explain what exactly you want to do with this BC array representation you mentioned

Of course! I use the resulting array in selectbox values where keys have the be the enum values. So far so good. And the values are translated by a translator for the user.

> I'm unsure if we should add more functionality to our enum class, or whether your specific problem can be solved in another way.

I don't think this deserves any functionality built in the Enum. The use case is very specific.

> `array_combine(array_keys($array), array_keys($array))` also isn't what was done before.

Ok, good to know, thanks.

The only problem here was that it was not mentioned in the bc breaks. That is fixed now, so no problem here.

The not so related problem is the fact that the Enum class cannot be extended in the traditional way. But it has its own [ticket](https://github.com/spatie/enum/issues/27) :-)

**Comment by josefsabl** [comment]
> Would you be fine with the old "private" method naming like `_toArrayBcCompat()` 

I don't understand this part too much :-)

> or would you like an annotation more `@ignoreEnum`

I would personally prefer the oposite: `@enumValue` for static methods that ARE supposed to generate the enum value. That would preserve the traditional extension behaviour and prevent developers from getting confused. It would also make fit into README very well :-)

**Comment by Gummibeer** [comment]
@josefsabl whitelisting the static methods would be a BC again. And I think that using public static methods for enum value is quite more common than using them for business logic. So I would stay with the blacklist approach.

@brendt should we implement this? If so an idea/wish how to?

**Comment by brendt** [comment]
To be honest, I don't think we should. An enum class represents an enum, and that's it. Let's not overcomplicate the developer's experience by introducing ways of whitelisting or blacklisting methods.

**Comment by Gummibeer** [comment]
Because @brendt and I talked about "better solutions" and if we should allow custom methods I will for sure share our ideas @josefsabl .

Our solution would be:
1) update your code/app like it's most times required if you do a major package update
2) override the `toArray()` method if you want to keep the old return array structure
3) use some kind of view-model or any other "middleware" to `array_combine()` the `getNames()` and/or `getValues()` method by your own and put them in the translator if you want to via `array_map()`

https://github.com/spatie/enum/releases/tag/2.1.1 is released so you can override all existing methods.

**Comment by josefsabl** [comment]
> 3\. use some kind of view-model or any other "middleware"

Yea, sure, I went this way.
