### ISSUE TITLE
Public function is detected as a static function

### ISSUE THREAD

**Issue by msiemens** [spatie/enum#31]
Hey there!

I have a enum defined like this:

```php
/**
 * @method static self category()
 * @method static self cmsPage()
 * @method static self product()
 */
class ObjectType extends Enum
{
    public function createModel()
    {
        // ...
    }
}
```

When creating a new instance with `ObjectType::make`, I get the following error:

```
ErrorException: forward_static_call() expects parameter 1 to be a valid callback, non-static method ObjectType::createModel() should not be called statically
.../vendor/spatie/enum/src/Enum.php:180
.../vendor/spatie/enum/src/Enum.php:239
.../vendor/spatie/enum/src/Enum.php:113
.../vendor/spatie/enum/src/Enum.php:203
.../vendor/spatie/enum/src/Enum.php:332
.../vendor/spatie/enum/src/Enum.php:176
```

From debugging this a little I can see that `createModel` is detected as a static method in https://github.com/spatie/enum/blob/93154c3f868cd491991fb2fde13f7b2f54f4f4aa/src/Enum.php#L291-L300

The reason seems to be that `getMethods`' filter parameter is equivalent to an OR test:

> Any bitwise disjunction of ReflectionMethod::IS_STATIC, ReflectionMethod::IS_PUBLIC, ReflectionMethod::IS_PROTECTED, ReflectionMethod::IS_PRIVATE, ReflectionMethod::IS_ABSTRACT, ReflectionMethod::IS_FINAL, so that all methods with any of the given attributes will be returned.
> (https://www.php.net/manual/en/reflectionclass.getmethods.php)

So it seems like it matches all methods that are *either* public *or* static.

**Comment by msiemens** [comment]
If wanted, I can try to provide a PR for this 🙃

**Comment by brendt** [comment]
I haven't tried this out, but my guess is that it should work with `ReflectionMethod::IS_STATIC & ReflectionMethod::IS_PUBLIC`

Feel free to submit a PR.

**Comment by msiemens** [comment]
PR submitted in #32 🙂

**Comment by Gummibeer** [comment]
https://github.com/spatie/enum/releases/tag/2.1.2
