### ISSUE TITLE
I cant migrate my table with the foreign key

### ISSUE THREAD

**Issue by hussainabuhajjaj** [spatie/enum#38]
2   PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `caddo`.`project_translations` (errno: 150 "Foreign key constraint is incorrectly formed")")
      C:\xampp\htdocs\caddotrading\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117

```
   Schema::create('project_translations', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedInteger('project_id');
            $table->string('name');
            $table->text('description');
            $table->string('locale')->index();
            $table->unique(['project_id','locale']);
            $table->foreign('project_id')->references('id')->on('projects')->onDelete('cascade');
            $table->timestamps();
        });
```

**Comment by Gummibeer** [comment]
Hey,
this package has nothing to do with PDO/Laravel or any other database related stuff.

If I would have to guess I would say that your issue belongs to https://github.com/Astrotomic/laravel-translatable ? 🤔
