### ISSUE TITLE
Get a random value for seeds

### ISSUE THREAD

**Issue by AurelGit** [spatie/enum#40]
Hey Spatie team !

First me and my team definitely love your job (a postcard is ready to be sent ^^)

What do you think about a `MyEnum::rand()` method to use it into factories / seeds ?
Is it useless or it could be interesting to open a PR ?

Thanks !

**Comment by brendt** [comment]
That's something that doesn't belong in this package, I would do this:

```php
collect(MyEnum::getAll())->random();
```
