### ISSUE TITLE
Map  by name=>value

### ISSUE THREAD

**Issue by dionysiosarvanitis** [spatie/enum#57]
Hi, is there any way to get something like below:

```php
class SaveStatus extends Enum
{
    public static function toArray(): array
    {
        return array_combine(static::getNames(), static::getValues());
    }
}
```
I use names instead of indexes so the mapping should be name=>value

**Comment by Gummibeer** [comment]
Hey,

you've already posted the solution. Just put this into your own base `Enum` class and extend this with all your enums.

```php
namespace App\Enums;

abstract class Enum extends \Spatie\Enum\Enum
{
    public static function toArray(): array
    {
        return array_combine(static::getNames(), static::getValues());
    }
}

final class SaveStatus extends \App\Enums\Enum {}
```

**Comment by dionysiosarvanitis** [comment]
Hi! Thank you for answering.

I tried what you said, but I got error on initialization. Constructor's 3rd argument `$index` must be an `int`. Overriding it is not enough because `getIndex()` must also return `int`.

public function __construct(?string $name = null, ?string $value = null, **?int** $index = null)

self::$cache[$class][$name]['index'] = static::make($name)->**getIndex()**;

**Comment by Gummibeer** [comment]
Good point, right now we depend on the `toArray()` method in resolve logic.
This should be changed. I think that this is changed by @brendt in v3 #56 
For the moment you could add your own method to achieve what you need.

**Comment by Gummibeer** [comment]
@dionysiosarvanitis I've added a PR #58 that drops the usage of `toArray()` in the `Enum` class itself.

**Comment by Gummibeer** [comment]
https://github.com/spatie/enum/releases/tag/2.3.7

**Comment by dionysiosarvanitis** [comment]
Works great. Thanks!
