### ISSUE TITLE
The given value is not available in this enum

### ISSUE THREAD

**Issue by dionysiosarvanitis** [spatie/enum#61]
Hi!

Is the intended behaviour to throw an Exception whille calling enum statically with wrong value?

`Approver::isDirector('wrong name')`

Is there any other way to use the short type of call instead of doing

`Approver::director()->isEqual($employee->getRole())`

Thanks

**Comment by Gummibeer** [comment]
You are right that a `try-catch` block is missing there. We've added one in the `isEqual()` method some time ago but forgot the magic methods.
Would you add it in a PR?
I will check how this impacts the coming v3 #56
