### ISSUE TITLE
Start index from one and custom logic

### ISSUE THREAD

**Issue by danieletulone** [spatie/enum#63]
Hi, I'm using spatie/enum by one day and I want to create enum with values that have index from 1 to N instead of 0 to N - 1.
I've created a class that extends Enum class and override the resolve method, adding `+ 1 `.

Code:

```php

protected static function resolve(): array
{

   // Code ...

   foreach ($values as $index => $value) {
        $name = strtoupper($value);

        self::$cache[$class][$name] = [
            'name' => $name,
            'index' => static::getMappedIndex($name) ?? $index + 1,
            'value' => static::getMappedValue($name) ?? $value,
        ];
    }

    // Code ...
}
```

Is the right way or is there another way to do this? (without use MAP_INDEX)
If no, why not to create a new property or function to use inner the foreach?

**Comment by Gummibeer** [comment]
Hey,

the wanted/public way to do this is the index map or overriding `getIndex()`. Both ways will change or be dropped in v3 #56 

Also the resolve logic will change in v3. The goal of v3 ist to simplify the code/class. Right now it's not done - so if you feel that a major feature is missing or removed you can tell @brendt & me.

**Comment by danieletulone** [comment]
Thanks for your time!
