### ISSUE TITLE
Feature regression with values and labels

### ISSUE THREAD

**Issue by gaelreyrol** [spatie/enum#66]
Hi,

With the v2, I had access to static methods `getNames` and `getValues`.

In the v3, I understand they are now accessible with `labels` and `values` but these are now protected and doesn't return default labels & values. 

For example, it was very helpful to automatically build a select from an enum.

I don't know if this was intended for this new major version. Would it be acceptable to restore this behavior ?

Regards

**Comment by Gummibeer** [comment]
Wouldn't the `toArray()` method be exactly what you want/need?
https://github.com/spatie/enum/blob/70c65164b8ab6f2c2a009b6f00aea4e9d507c7ec/src/Enum.php#L26-L35
For selects you can map it to value and label and if you need only one you can use `array_values()` or `array_keys()` depending on your needs.

**Comment by gaelreyrol** [comment]
Absolutely, I am sorry for the inconvenience, I should have looked more carefully !

**Comment by Gummibeer** [comment]
Everything fine. 🙂
I know that v3 changed a lot.
