### ISSUE TITLE
Switch operator usage

### ISSUE THREAD

**Issue by GSpecDrum** [spatie/enum#67]
Hello! Thanks for this library!

I have a question:
May I use this enums in switch operators? Have usage of this library with switch operator some pitfalls?

**Comment by Gummibeer** [comment]
Hey,

yes you can use the enums in a switch statement like follows:

```php
switch(Gender::MALE()) {
  case Gender::FEMALE():
    return 'female';
  case Gender::MALE():
    return 'male';
}
```

That's just a super stupid example but tested in a project and it perfectly works. 🙂

**Comment by GSpecDrum** [comment]
Thanks for fast and clear answer!
