### ISSUE TITLE
Method to retrieve a list of possible values

### ISSUE THREAD

**Issue by hackel** [spatie/enum#69]
I often find myself needing a list of acceptable enum values, such as to build a 'where in' database query, for example.  It would be convenient if I could just call `MyEnum::values()` and get a list of values instead of having to use `array_keys(MyEnum::toArray())` every time.

The implementation is simple, but I decided to open an issue as I'm not sure if this would be seen as necessary.

```php
    public static function __callStatic(string $name, array $arguments)
    {
        if ($name === 'values') {
            return array_keys(static::toArray());
        }

        return new static($name);
    }
```

I'm also not sure if this should use `array_keys` or `array_flip`—it might be useful to have the labels in some cases.  It also works fine when implementing a protected `values` method.

**Comment by Gummibeer** [comment]
Yeah, we had this discussed already sometimes.
I think that I would add the old `getValues()` and `getLabels()` methods from v2.
What do you want to do in a `where IN` DB query? 🤔 I mean in theory there shouldn't be a value in this column not part of the enum!?
Just asking if there would be something else we could add.

**Comment by hackel** [comment]
Well yes, but that particular example was for detecting records with bad data in a (very old) database.  Another example is choosing a random value in a model factory.  Nothing that can't be easily worked around, and I see a similar request was made in #66, so perhaps it's not worth it to increase the API surface.  I never used v2 myself, but it sounds like it could make it easier for people trying to upgrade?

**Comment by Gummibeer** [comment]
The factory, as long as you use Laravel, is added to the Laravel wrapper with a faker provider.
But yeah, I think adding these two methods isn't too bad!? @brendt 🤔

**Comment by brendt** [comment]
I agree, but I'd keep these methods in line with the `toArray` implementation:

```php
MyEnum::values()
MyEnum::labels()
```

These methods can be added on the base enum, instead of via `__callStatic`. One would return `array_keys(static::toArray())` and the other would return `array_values(static::toArray())`. I'd explicitly _not_ keep the keys or use `array_flip`. If you're using these methods you're only interested in that data. Otherwise you could use `toArray` directly.

Thoughts?

Are you able to PR this @hackel ?

**Comment by Gummibeer** [comment]
@brendt we can't use values/labels as they are the map methods.
So we have to use the getValues/Labels.

**Comment by brendt** [comment]
Right, it was early morning and I hadn't had my coffee yet 😅

A getter indicates an instance method though, not a static one… I'm just going to throw some idea on here, please provide feedback:

- `getValues` and `getLabels` as instance methods, which I find strange `MyEnum::SomeValue()->getLabels()`
- `getValues` and `getLabels` as static methods: `MyEnum::getValues()`
- `asValues` and `asLabels`: `MyEnum::asValues()`
- `toValues` and `toLabels`: `MyEnum::toValues()`
- Expose the definition: `MyEnum::definition()->getValues()` — we could choose another name for `::definition`

That's all the idea I have at the moment…

**Comment by Gummibeer** [comment]
I prefer static getters as in v2.
Exposing the definition doesn't feel right as it's marked as `internal` and the properties are public. So exposing it would mean that the user could, unintentionally, manipulate the enum.

**Comment by brendt** [comment]
Let's add it like so, and discuss the naming in the PR: so `MyEnum::getLabels()` and `MyEnum::getValues()`.

I'll wait until tomorrow to check whether @hackel wants to do it, otherwise I'll submit a PR myself.
