### ISSUE TITLE
Support standard strict comparison

### ISSUE THREAD

**Issue by SamMousa** [spatie/enum#93]
Currently each instantiation of an enum creates a new object, this makes comparing instances hard.

Since we already have a static constructor we could consider improving the DX:
1. Make the constructor private & final
2. Instead of creating a new object on every call to `make()` we only create 1 per value.

This will allow normal strict comparisons to work: `$enum1 === $enum2`.

Note that the normal advantage of the flyweight pattern, reduced memory usage, is not really relevant here this is more about DX with respect to using normal comparison operators.

I think this also aligns with how 8.1 will implement enums.

**Comment by Gummibeer** [comment]
Hey,
as that's what PHP8.1 enums will do - yes.
I will accept a PR adding this. There's no downside as nothing in the enums is intended to be changed between instances but with the same value.

So even `Status::DRAFT()->color()` should always return `gray`.
It aligns with #79 as part of reducing PHP8.1 breakiness. 🎉

**Comment by wsamoht** [comment]
Can you think of a way to get strict comparison to work with an object that has been unserialized? My use case is storing an object with an enum property in cache using Laravel. I was using strict comparison in my code but then started to get unexpected results when I added caching.

I tried messing around with `__serialize` and `__unserialize` within the `Enum` class but I am thinking it is impossible as PHP will always create a new instance of the class. There is no way to tell it to use a different instance upon unserialization. It seems that I will just need to use the `equals()` method.

**Comment by SamMousa** [comment]
We could make it work for the case where only 1 instance is cached, and that instance is unserialized before another instance is created. This would be done by storing the reference in the unserialize call; it'd be a very ugly hack though.

**Comment by wsamoht** [comment]
Sounds like that wouldn't be a good idea then :) Do you think a note should be made in the README about not using strict comparison `===` if the data is going to be serialized/unserialized? Maybe it doesn't matter since enumerations in 8.1 will work just fine with strict comparison ([reference](https://wiki.php.net/rfc/enumerations#serialization)).

**Comment by SamMousa** [comment]
A note never hurts!
